### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by kachkaev** [mxschmitt/playwright-test-coverage#11]
👋 @mxschmitt! Great library, I love it!

I was [experimenting](https://github.com/blockprotocol/blockprotocol/pull/447) with Playwright today and had to add local typings for `playwright-test-coverage`:

```ts
// playwright-test-coverage.d.ts
declare module "playwright-test-coverage" {
  export * from "@playwright/test";
}
```

WDYT of including the typings so that other folks did not have to do this? Writing Playwright tests in TS must be quite common.

**Comment by mxschmitt** [comment]
This is the wrong repo, you need to file it against `https://github.com/anishkny/playwright-test-coverage`.

**Comment by kachkaev** [comment]
You’re right, thanks for pointing this out! 😅 ➡️ https://github.com/anishkny/playwright-test-coverage/issues/53
