### ISSUE TITLE
Support Playwright component testing

### ISSUE THREAD

**Issue by iamdhruv** [mxschmitt/playwright-test-coverage#16]

**Comment by SabFloki** [comment]
@mxschmitt  Does this setup be used the same for @playwright-experimental-react? Component testing?

**Comment by beamery-tomht** [comment]
Same question

**Comment by aniketicloud** [comment]
He added the code for coverage for component testing in `ct-react-vite` branch.

**Comment by mxschmitt** [comment]
https://github.com/mxschmitt/playwright-test-coverage/tree/ct-react-vite
