### ISSUE TITLE
Can we do test coverage for component testing?

### ISSUE THREAD

**Issue by aniketicloud** [mxschmitt/playwright-test-coverage#25]
Just like Vitest/Jest, can we do a code coverage in component testing in Playwright?

**Comment by mxschmitt** [comment]
In theory, the same concept of this repository can be applied to component testing. This would require adjusting the [ctViteConfig](https://playwright.dev/docs/test-components#i-have-a-project-that-already-uses-vite-can-i-reuse-the-config) to include the coverage plugin and collect it.

**Comment by aniketicloud** [comment]
Thank you for adding the component testing coverage example. It is in `ct-react-vite` branch.
https://github.com/mxschmitt/playwright-test-coverage/tree/ct-react-vite
